/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.EmployeeDao;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employees;

/**
 *
 * @author MSI
 */
public class AplikasiUtama extends javax.swing.JFrame {
        PanelCountries countries = new PanelCountries();
        PanelDepartments departments = new PanelDepartments();
        PanelEmployee employees = new PanelEmployee();
        PanelJobs jobs = new PanelJobs();
        PanelLocations locations = new PanelLocations();
        PanelRegions regions = new PanelRegions();
        DefaultTableModel dtmEmployee;
        EmployeeDao daoEmployee;
    /**
     * Creates new form AplikasiUtama
     */
    public AplikasiUtama() {
        initComponents();
        this.add(countries);
        this.add(departments);
        this.add(employees);
        this.add(jobs);
        this.add(locations);
        this.add(regions);
        daoEmployee = new EmployeeDao();
        dtmEmployee = (DefaultTableModel) tabelEmp.getModel();
        logout();
        DataEmployee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelLogin = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelEmp = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        rgions = new javax.swing.JMenuItem();
        country = new javax.swing.JMenuItem();
        loc = new javax.swing.JMenuItem();
        depart = new javax.swing.JMenuItem();
        job = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        employee = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi HR");
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelLogin.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 24, 231, 0);
        panelLogin.add(jButton1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 5, 0, 224);
        panelLogin.add(pass, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(219, 5, 0, 224);
        panelLogin.add(user, gridBagConstraints);

        jLabel1.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(222, 218, 0, 0);
        panelLogin.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 218, 0, 0);
        panelLogin.add(jLabel2, gridBagConstraints);

        getContentPane().add(panelLogin, "card2");

        panelHome.setLayout(new java.awt.GridBagLayout());

        tabelEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Job Title", "Department Name", "Hire Date", "Salary", "Email", "Phone Number", "City", "Country", "Region"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelEmp);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 581;
        gridBagConstraints.ipady = 454;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 13, 12);
        panelHome.add(jScrollPane1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Data Karyawan Aktif");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 224, 0, 0);
        panelHome.add(jLabel3, gridBagConstraints);

        getContentPane().add(panelHome, "card3");

        jMenu1.setText("File");

        jMenuItem1.setText("LogOut");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("MasterData");

        rgions.setText("Regions");
        rgions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgionsActionPerformed(evt);
            }
        });
        jMenu2.add(rgions);

        country.setText("Countries");
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        jMenu2.add(country);

        loc.setText("Locations");
        loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locActionPerformed(evt);
            }
        });
        jMenu2.add(loc);

        depart.setText("Departments");
        depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departActionPerformed(evt);
            }
        });
        jMenu2.add(depart);

        job.setText("Jobs");
        job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobActionPerformed(evt);
            }
        });
        jMenu2.add(job);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Employee");

        employee.setText("Employees");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        jMenu3.add(employee);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JOptionPane.showMessageDialog(this, "Good bye Admin! \nExit", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void departActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departActionPerformed
        department();
    }//GEN-LAST:event_departActionPerformed

    private void jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobActionPerformed
        job();
    }//GEN-LAST:event_jobActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        country();
    }//GEN-LAST:event_countryActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        employee();
    }//GEN-LAST:event_employeeActionPerformed

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
        locationx();
    }//GEN-LAST:event_locActionPerformed

    private void rgionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgionsActionPerformed
        region();
    }//GEN-LAST:event_rgionsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (user.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (pass.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Password Pinjam is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (user.getText().equals("admin")  && pass.getText().equals("admin12345*")) {
            JOptionPane.showMessageDialog(this, "Welcome admin", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            home();
        }else{
            JOptionPane.showMessageDialog(this, "Username atau Password salah", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Good bye Admin! \nLogOut", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        logout();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem country;
    private javax.swing.JMenuItem depart;
    private javax.swing.JMenuItem employee;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem job;
    private javax.swing.JMenuItem loc;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField pass;
    private javax.swing.JMenuItem rgions;
    private javax.swing.JTable tabelEmp;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
    private void logout() {
        jMenuBar1.setVisible(false);
        panelLogin.setVisible(true);
        panelHome.setVisible(false);
        countries.setVisible(false);
        departments.setVisible(false);
        employees.setVisible(false);
        jobs.setVisible(false);
        locations.setVisible(false);
        regions.setVisible(false);
    }
  
    private void home() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        DataEmployee();
        panelHome.setVisible(true);
        countries.setVisible(false);
        departments.setVisible(false);
        employees.setVisible(false);
        jobs.setVisible(false);
        locations.setVisible(false);
        regions.setVisible(false);
    }
  
    private void region() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        countries.setVisible(false);
        departments.setVisible(false);
        employees.setVisible(false);
        jobs.setVisible(false);
        locations.setVisible(false);
        regions.reset();
        regions.setVisible(true);
    }
  
    private void country() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        countries.reset();
        countries.setVisible(true);
        departments.setVisible(false);
        employees.setVisible(false);
        jobs.setVisible(false);
        locations.setVisible(false);
        regions.setVisible(false);
    }
  
    private void locationx() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        countries.setVisible(false);
        departments.setVisible(false);
        employees.setVisible(false);
        jobs.setVisible(false);
        locations.reset();
        locations.setVisible(true);
        regions.setVisible(false);
    }
  
    private void department() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        countries.setVisible(false);
        departments.reset();
        departments.setVisible(true);
        employees.setVisible(false);
        jobs.setVisible(false);
        locations.setVisible(false);
        regions.setVisible(false);
    }
  
    private void job() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        countries.setVisible(false);
        departments.setVisible(false);
        employees.setVisible(false);
        jobs.reset();
        jobs.setVisible(true);
        locations.setVisible(false);
        regions.setVisible(false);
    }
  
    private void employee() {
        jMenuBar1.setVisible(true);
        panelLogin.setVisible(false);
        panelHome.setVisible(false);
        countries.setVisible(false);
        departments.setVisible(false);
        employees.reset();
        employees.setVisible(true);
        jobs.setVisible(false);
        locations.setVisible(false);
        regions.setVisible(false);
    }
    
    public void DataEmployee() {
        dtmEmployee.getDataVector().removeAllElements();
        for (Employees b : daoEmployee.getAllData()) {
            dtmEmployee.addRow(new Object[]{
                b.getEmployeeId(),
                b.getFirstName() + "" + b.getLastName(),
                b.getJobId().getJobTitle(),
                (b.getDepartmentId() == null) ? "-" : b.getDepartmentId().getDepartmentName(),
                formatDate.sdf.format(b.getHireDate()),
                Double.valueOf(b.getSalary()),
                b.getEmail(),
                b.getPhoneNumber(),
                (b.getDepartmentId() == null) ? "-" : b.getDepartmentId().getLocationId().getCity(),
                (b.getDepartmentId() == null) ? "-" : b.getDepartmentId().getLocationId().getCountryId().getCountryName(),
                (b.getDepartmentId() == null) ? "-" : b.getDepartmentId().getLocationId().getCountryId().getRegionId().getRegionName()
            });
        }
    }
    public class formatDate{
        public static SimpleDateFormat sdf = new SimpleDateFormat("EEE, dd MMM yyyy");
    }
}
